### ISSUE TITLE
MapperParsingException[failed to parse]; nested: NoClassDefFoundError[Could not initialize class com.drew.imaging.jpeg.JpegMetadataReader];

### ISSUE THREAD

**Issue by Artgit** [kiwionly/elasticsearch-image#10]
I'm trying to index my images. Png file indexes without exceptions, but jpeg file throws:

```
MapperParsingException[failed to parse]; nested: NoClassDefFoundError[Could not initialize class com.drew.imaging.jpeg.JpegMetadataReader];
        at org.elasticsearch.index.mapper.DocumentParser.parseDocument(DocumentParser.java:154)
        at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:309)
        at org.elasticsearch.index.shard.IndexShard.prepareCreate(IndexShard.java:529)
        at org.elasticsearch.index.shard.IndexShard.prepareCreateOnPrimary(IndexShard.java:506)
        at org.elasticsearch.action.index.TransportIndexAction.prepareIndexOperationOnPrimary(TransportIndexAction.java:215)
        at org.elasticsearch.action.index.TransportIndexAction.executeIndexRequestOnPrimary(TransportIndexAction.java:224)
        at org.elasticsearch.action.index.TransportIndexAction.shardOperationOnPrimary(TransportIndexAction.java:158)
        at org.elasticsearch.action.index.TransportIndexAction.shardOperationOnPrimary(TransportIndexAction.java:66)
        at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryPhase.doRun(TransportReplicationAction.java:639)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
        at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.java:279)
        at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.java:271)
        at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:75)
        at org.elasticsearch.transport.TransportService$4.doRun(TransportService.java:376)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.drew.imaging.jpeg.JpegMetadataReader
        at com.drew.imaging.ImageMetadataReader.readMetadata(ImageMetadataReader.java:98)
        at org.elasticsearch.index.mapper.image.ImageMapper.parse(ImageMapper.java:407)
        at org.elasticsearch.index.mapper.DocumentParser.parseObjectOrField(DocumentParser.java:309)
        at org.elasticsearch.index.mapper.DocumentParser.parseValue(DocumentParser.java:436)
        at org.elasticsearch.index.mapper.DocumentParser.parseObject(DocumentParser.java:262)
        at org.elasticsearch.index.mapper.DocumentParser.parseDocument(DocumentParser.java:122)
        ... 17 more

```

what am I doing wrong ?

**Comment by ghost** [comment]
@kiwionly . Please help me to solve this issue?

**Comment by kiwionly** [comment]
This look like the mapper cannot find the meta extractor library.

make sure the lib is in the elastic image folder.

**Comment by kiwionly** [comment]
I had fixed one issue which xmp core library missing. 

please pull the latest code and rebuild the plugin.
