### ISSUE TITLE
Cannot start ES2.3.4 after adding this plugin

### ISSUE THREAD

**Issue by victorfang** [kiwionly/elasticsearch-image#12]
1, I copied this folder into the `elasticsearch-2.3.4/plugins/` and extracted

2, successfully ran `gradle plugin`

3, I was able to start my ES2.3.4 successfully prior to adding this plugin. 

4, When I try to start ES2.3.4  w/ this plugin , I got this error:

bin/elasticsearch

```
[2016-07-12 00:01:27,695][INFO ][node                     ] [Celestial Madonna] version[2.3.4], pid[2347], build[e455fd0/2016-06-30T11:24:31Z]
[2016-07-12 00:01:27,696][INFO ][node                     ] [Celestial Madonna] initializing ...
Exception in thread "main" java.lang.IllegalStateException: Could not load plugin descriptor for existing plugin [elasticsearch-image]. Was the plugin built before 2.0?
Likely root cause: java.nio.file.NoSuchFileException: somepath/elasticsearch-2.3.4/plugins/elasticsearch-image/plugin-descriptor.properties
    at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
    at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
    at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
    at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
    at java.nio.file.Files.newByteChannel(Files.java:361)
    at java.nio.file.Files.newByteChannel(Files.java:407)
    at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384)
    at java.nio.file.Files.newInputStream(Files.java:152)
    at org.elasticsearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:87)
    at org.elasticsearch.plugins.PluginsService.getPluginBundles(PluginsService.java:378)
    at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:128)
    at org.elasticsearch.node.Node.<init>(Node.java:158)
    at org.elasticsearch.node.Node.<init>(Node.java:140)
    at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:143)
    at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:178)
    at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:270)
    at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)
Refer to the log for complete error details.
```

**Comment by kiwionly** [comment]
you need to make sure the plugin descriptor e.s version match the current E.S version u using.

mean you need to do sth like this in plugin descriptor : 

elasticsearch.version=2.3.4
