### ISSUE TITLE
 ElasticsearchImageProcessException[Failed to index feature LOCAL_BINARY_PATTERNS]

### ISSUE THREAD

**Issue by ghost** [kiwionly/elasticsearch-image#18]
MapperParsingException[failed to parse]; nested: ElasticsearchImageProcessException[Failed to index feature LOCAL_BINARY_PATTERNS]; nested: ArrayIndexOutOfBoundsException;
    at org.elasticsearch.index.mapper.DocumentParser.parseDocument(DocumentParser.java:154)
    at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:309)
    at org.elasticsearch.index.shard.IndexShard.prepareCreate(IndexShard.java:529)
    at org.elasticsearch.index.shard.IndexShard.prepareCreateOnPrimary(IndexShard.java:506)
    at org.elasticsearch.action.index.TransportIndexAction.prepareIndexOperationOnPrimary(TransportIndexAction.java:215)
    at org.elasticsearch.action.index.TransportIndexAction.executeIndexRequestOnPrimary(TransportIndexAction.java:224)
    at org.elasticsearch.action.index.TransportIndexAction.shardOperationOnPrimary(TransportIndexAction.java:158)
    at org.elasticsearch.action.index.TransportIndexAction.shardOperationOnPrimary(TransportIndexAction.java:66)
    at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryPhase.doRun(TransportReplicationAction.java:639)
    at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
    at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.java:279)
    at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.java:271)
    at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:75)
    at org.elasticsearch.transport.TransportService$4.doRun(TransportService.java:376)
    at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: ElasticsearchImageProcessException[Failed to index feature LOCAL_BINARY_PATTERNS]; nested: ArrayIndexOutOfBoundsException;
    at org.elasticsearch.index.mapper.image.ImageMapper.parse(ImageMapper.java:400)
    at org.elasticsearch.index.mapper.DocumentParser.parseObjectOrField(DocumentParser.java:309)
    at org.elasticsearch.index.mapper.DocumentParser.parseValue(DocumentParser.java:436)
    at org.elasticsearch.index.mapper.DocumentParser.parseObject(DocumentParser.java:262)
    at org.elasticsearch.index.mapper.DocumentParser.parseDocument(DocumentParser.java:122)
    ... 17 more
Caused by: java.lang.ArrayIndexOutOfBoundsException

**Comment by kiwionly** [comment]
Which version of Elasticsearch image you using ?

**Comment by ghost** [comment]
i'm using elasticsearch-2.3.4 and elasticsearch-image on brand master.

**Comment by rezaAdie** [comment]
hi, is this plugin support for elasticsearch 5???

**Comment by kiwionly** [comment]
not really try it, it may not supported.

**Comment by rezaAdie** [comment]
Ok, i have tried and it not support, and make me can't run my elastic, but is there a way to make it supported??? is there spesific place i need to edit in plugin???

**Comment by kiwionly** [comment]
I not sure, You may download the code and see how it could be supported.

**Comment by rezaAdie** [comment]
hi, @kiwionly, i already download it, and i'm export it as maven project in eclipse, but i got error on `import net.semanticmetadata.lire.` i try to search it in pom, but i can't find it,, where do you get this import??? i try to search in maven dependency, but it link to this github to.

**Comment by kiwionly** [comment]
the lib is in the lib folder. you need to manually copy this lib since it not available in maven. If you want to build, I will suggest using gradle instead.
