### ISSUE TITLE
Caused by: NotSerializableExceptionWrapper[Failed to index feature PHOG]; nested: ArrayIndexOutOfBoundsException;

### ISSUE THREAD

**Issue by minusmajun** [kiwionly/elasticsearch-image#21]
Exception in thread "main" MapperParsingException[failed to parse]; nested: NotSerializableExceptionWrapper[Failed to index feature PHOG]; nested: ArrayIndexOutOfBoundsException;
	at org.elasticsearch.index.mapper.DocumentParser.innerParseDocument(DocumentParser.java:159)
	at org.elasticsearch.index.mapper.DocumentParser.parseDocument(DocumentParser.java:79)
	at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:304)
	at org.elasticsearch.index.shard.IndexShard.prepareCreate(IndexShard.java:517)
	at org.elasticsearch.index.shard.IndexShard.prepareCreate(IndexShard.java:508)
	at org.elasticsearch.action.support.replication.TransportReplicationAction.prepareIndexOperationOnPrimary(TransportReplicationAction.java:1054)
	at org.elasticsearch.action.support.replication.TransportReplicationAction.executeIndexRequestOnPrimary(TransportReplicationAction.java:1062)
	at org.elasticsearch.action.index.TransportIndexAction.shardOperationOnPrimary(TransportIndexAction.java:170)
	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryPhase.performOnPrimary(TransportReplicationAction.java:580)
	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryPhase$1.doRun(TransportReplicationAction.java:453)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: NotSerializableExceptionWrapper[Failed to index feature PHOG]; nested: ArrayIndexOutOfBoundsException;
	at org.elasticsearch.index.mapper.image.ImageMapper.parse(ImageMapper.java:388)
	at org.elasticsearch.index.mapper.DocumentParser.parseObjectOrField(DocumentParser.java:314)
	at org.elasticsearch.index.mapper.DocumentParser.parseValue(DocumentParser.java:441)
	at org.elasticsearch.index.mapper.DocumentParser.parseObject(DocumentParser.java:267)
	at org.elasticsearch.index.mapper.DocumentParser.innerParseDocument(DocumentParser.java:127)
	... 13 more
Caused by: java.lang.ArrayIndexOutOfBoundsException

**Comment by kiwionly** [comment]
Hi,

which version of E.S and E.S image you using ?
