### ISSUE TITLE
elasticsearch 2.20 Could not find plugin class [org.elasticsearch.plugin.image.ImagePlugin]

### ISSUE THREAD

**Issue by deter3** [kiwionly/elasticsearch-image#5]
Elasticsearch 2.2.0 , Java 1.8 (original 1.7 , since elasticsearch-image requires 1.8 , just upgraded ) 

When I start elasticsearch server , i got 

```
[2016-05-25 06:06:14,054][INFO ][node                     ] [homer] initializing ...
Exception in thread "main" ElasticsearchException[Could not find plugin class [org.elasticsearch.plugin.image.ImagePlugin]]; nested: ClassNotFoundException[org.elasticsearch.plugin.image.ImagePlugin];
Likely root cause: java.lang.ClassNotFoundException: org.elasticsearch.plugin.image.ImagePlugin
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:814)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at org.elasticsearch.plugins.PluginsService.loadPluginClass(PluginsService.java:463)
    at org.elasticsearch.plugins.PluginsService.loadBundles(PluginsService.java:431)
    at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:129)
    at org.elasticsearch.node.Node.<init>(Node.java:146)
    at org.elasticsearch.node.Node.<init>(Node.java:128)
    at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:145)
    at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:178)
    at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:285)
    at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)
```

If i remove elasticsearch-image  , server start without  problem .

does anybody know how to fix it ? I know few about Java .

**Comment by kiwionly** [comment]
see here for how to install ES image.

[https://github.com/kiwionly/elasticsearch-image/issues/2](https://github.com/kiwionly/elasticsearch-image/issues/2)
