### ISSUE TITLE
has unsupported parameters

### ISSUE THREAD

**Issue by thangman22** [kiwionly/elasticsearch-image#7]
I try to create mapping for index follow this request
`curl -XPUT 'http://192.168.1.107:9299/images/_mapping/images?pretty=true' -d '{
    "images": {
        "properties": {
            "my_img": {
                "type": "image",
                "feature": {
                    "CEDD": {
                        "hash": "BIT_SAMPLING"
                    },
                    "JCD": {
                        "hash": ["BIT_SAMPLING", "LSH"]
                    }
                },
                "metadata": {
                    "jpeg.image_width": {
                        "type": "string",
                        "store": "yes"
                    },
                    "jpeg.image_height": {
                        "type": "string",
                        "store": "yes"
                    }
                }
            }
        }
    }
}'`

and this is response

`{
  "error" : {
    "root_cause" : [ {
      "type" : "mapper_parsing_exception",
      "reason" : "Mapping definition for [my_img] has unsupported parameters:  [feature : {CEDD={hash=[BIT_SAMPLING]}, JCD={hash=[BIT_SAMPLING, LSH]}}] [metadata : {jpeg.image_width={type=string}, jpeg.image_height={type=string}}]"
    } ],
    "type" : "mapper_parsing_exception",
    "reason" : "Mapping definition for [my_img] has unsupported parameters:  [feature : {CEDD={hash=[BIT_SAMPLING]}, JCD={hash=[BIT_SAMPLING, LSH]}}] [metadata : {jpeg.image_width={type=string}, jpeg.image_height={type=string}}]"
  },
  "status" : 400
}`

what any happen?

**Comment by Artgit** [comment]
I have the same issue.

I have manually installed plugin by a following scenario:

```
1. Get the the master release of elasticsearch-image
2. Inside elasticsearch-image run gradle plugin
3. Tell ES to install the result of the gradle build bin\plugin install file:///...elasticsearch-image-2.3.3.zip 
```

and started Elasticsearch.

Then I have created an index:

`curl -XPUT "http://localhost:9200/test"`

and tried to apply mapping:

```
curl -XPUT 'localhost:9200/test/test/_mapping' -d '{
    "test": {
        "properties": {
            "my_img": {
                "type": "image",
                "feature": {
                    "CEDD": {
                        "hash": "BIT_SAMPLING"
                    },
                    "JCD": {
                        "hash": ["BIT_SAMPLING", "LSH"]
                    }
                },
                "metadata": {
                    "jpeg.image_width": {
                        "type": "string",
                        "store": "yes"
                    },
                    "jpeg.image_height": {
                        "type": "string",
                        "store": "yes"
                    }
                }
            }
        }
    }
}'
```

It fails with a following error:

curl output:

`{"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"Mapping definition for [my_img] has unsupported parameters:  [feature : {CEDD={hash=[BIT_SAMPLING]}, JCD={hash=[BIT_SAMPLING, LSH]}}] [metadata : {jpeg.image_width={type=string}, jpeg.image_height={type=string}}]"}],"type":"mapper_parsing_exception","reason":"Mapping definition for [my_img] has unsupported parameters:  [feature : {CEDD={hash=[BIT_SAMPLING]}, JCD={hash=[BIT_SAMPLING, LSH]}}] [metadata : {jpeg.image_width={type=string}, jpeg.image_height={type=string}}]"},"status":400}`

Elasticsearch output:

```
[2016-07-02 17:41:26,971][DEBUG][action.admin.indices.mapping.put] [Primevil] failed to put mappings on indices [[test]], type [test]
MapperParsingException[Mapping definition for [my_img] has unsupported parameters:  [feature : {CEDD={hash=[BIT_SAMPLING]}, JCD={hash=[BIT_SAMPLING, LSH]}}] [metadata : {jpeg.image_width={type=string}, jpeg.image_height={type=string}}]]
        at org.elasticsearch.index.mapper.DocumentMapperParser.checkNoRemainingFields(DocumentMapperParser.java:171)
        at org.elasticsearch.index.mapper.DocumentMapperParser.checkNoRemainingFields(DocumentMapperParser.java:165)
        at org.elasticsearch.index.mapper.object.ObjectMapper$TypeParser.parseProperties(ObjectMapper.java:307)
        at org.elasticsearch.index.mapper.object.ObjectMapper$TypeParser.parseObjectOrDocumentTypeProperties(ObjectMapper.java:218)
        at org.elasticsearch.index.mapper.object.RootObjectMapper$TypeParser.parse(RootObjectMapper.java:139)
        at org.elasticsearch.index.mapper.DocumentMapperParser.parse(DocumentMapperParser.java:118)
        at org.elasticsearch.index.mapper.DocumentMapperParser.parse(DocumentMapperParser.java:99)
        at org.elasticsearch.index.mapper.MapperService.parse(MapperService.java:508)
        at org.elasticsearch.cluster.metadata.MetaDataMappingService$PutMappingExecutor.applyRequest(MetaDataMappingService.java:257)
        at org.elasticsearch.cluster.metadata.MetaDataMappingService$PutMappingExecutor.execute(MetaDataMappingService.java:230)
        at org.elasticsearch.cluster.service.InternalClusterService.runTasksForExecutor(InternalClusterService.java:468)
        at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:772)
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:231)
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:194)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

```

What am I doing wrong ?

**Comment by kiwionly** [comment]
That is an error in the sample code, features hash type must using json array, e.g. [BIT_SAMPLING].

I had update the readme.

**Comment by Artgit** [comment]
@kiwionly  thanks for your answer.

It still doesn't work even with an updated example in readme:

```
curl -XPUT 'localhost:9200/test/test/_mapping' -d '{
    "test": {
        "properties": {
            "my_img": {
                "type": "image",
                "feature": {
                    "CEDD": {
                        "hash": ["BIT_SAMPLING"]
                    },
                    "JCD": {
                        "hash": ["BIT_SAMPLING", "LSH"]
                    }
                },
                "metadata": {
                    "jpeg.image_width": {
                        "type": "string",
                        "store": "yes"
                    },
                    "jpeg.image_height": {
                        "type": "string",
                        "store": "yes"
                    }
                }
            }
        }
    }
}'
```

```
[2016-07-02 21:41:25,018][DEBUG][action.admin.indices.mapping.put] [Primevil] failed to put mappings on indices [[test]], type [test]
MapperParsingException[Mapping definition for [my_img] has unsupported parameters:  [feature : {CEDD={hash=[BIT_SAMPLING]}, JCD={hash=[BIT_SAMPLING, LSH]}}] [metadata : {jpeg.image_width={type=string}, jpeg.image_height={type=string}}]]
        at org.elasticsearch.index.mapper.DocumentMapperParser.checkNoRemainingFields(DocumentMapperParser.java:171)
        at org.elasticsearch.index.mapper.DocumentMapperParser.checkNoRemainingFields(DocumentMapperParser.java:165)
        at org.elasticsearch.index.mapper.object.ObjectMapper$TypeParser.parseProperties(ObjectMapper.java:307)
        at org.elasticsearch.index.mapper.object.ObjectMapper$TypeParser.parseObjectOrDocumentTypeProperties(ObjectMapper.java:218)
        at org.elasticsearch.index.mapper.object.RootObjectMapper$TypeParser.parse(RootObjectMapper.java:139)
        at org.elasticsearch.index.mapper.DocumentMapperParser.parse(DocumentMapperParser.java:118)
        at org.elasticsearch.index.mapper.DocumentMapperParser.parse(DocumentMapperParser.java:99)
        at org.elasticsearch.index.mapper.MapperService.parse(MapperService.java:508)
        at org.elasticsearch.cluster.metadata.MetaDataMappingService$PutMappingExecutor.applyRequest(MetaDataMappingService.java:257)
        at org.elasticsearch.cluster.metadata.MetaDataMappingService$PutMappingExecutor.execute(MetaDataMappingService.java:230)
        at org.elasticsearch.cluster.service.InternalClusterService.runTasksForExecutor(InternalClusterService.java:468)
        at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:772)
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:231)
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:194)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

```

P.S.

```
elasticsearch-2.3.3>bin\plugin list
Installed plugins in elasticsearch-2.3.3\plugins:
    - elasticsearch-image
```

What can be wrong now ?

**Comment by kiwionly** [comment]
make sure elastic image install successful (correct version etc).
make sure index is created successfully (e.g. following the sample setting.)
You should able to create the index successfully with the sample configuration.

hope this help.

**Comment by Artgit** [comment]
> > make sure elastic image install successful (correct version etc).

as you can see from my output - Image plugin is in place(installed from the following distribution elasticsearch-image\build\distributions\elasticsearch-image-2.3.3.zip ):

```
elasticsearch-2.3.3>bin\plugin list
Installed plugins in elasticsearch-2.3.3\plugins:
    - elasticsearch-image
```

> > make sure index is created successfully (e.g. following the sample setting.)

I tried both of these variants:

```
curl -XPUT 'http://localhost:9200/test/' -d '{
    "settings" : {
        "index" : {
            "number_of_shards" : 5, 
            "number_of_replicas" : 2
        }
    }
}'
```

and

```
curl -XPUT 'http://localhost:9200/test/' -d '{
    "settings" : {
        "index" : {
            "number_of_shards" : 5, 
            "number_of_replicas" : 2,
            "index.version.created" : 1070499 
        }
    }
}'
```

index is created successfully with no luck later with a mappings :(

**Comment by kiwionly** [comment]
Is index then  settings,  u can remove the index, see readme.

**Comment by kiwionly** [comment]
I using same code as readme, it should work.

**Comment by Artgit** [comment]
@kiwionly Thank you so much ! I got it working:

with

```
curl -XPUT 'http://localhost:9200/test/' -d '{
    "settings" : {
        "number_of_shards" : 5,
        "number_of_replicas" : 1,
        "index.version.created" : 1070499 
    }
}'
```
