### ISSUE TITLE
ERROR: Could not find plugin descriptor 'plugin-descriptor.properties' in plugin zip

### ISSUE THREAD

**Issue by Artgit** [kiwionly/elasticsearch-image#8]
On my Windows 10 machine I have downloaded ES 2.3.3 and trying to install elasticsearch-image plugin by a following command:

`bin\plugin install kiwionly/elasticsearch-image`

It fails with a following error:

```
elasticsearch-2.3.3>bin\plugin install kiwionly/elasticsearch-image
-> Installing kiwionly/elasticsearch-image...
Trying https://github.com/kiwionly/elasticsearch-image/archive/master.zip ...
Downloading ................................................................................................................................
............................................................................................................................................
............................................................................................................................................
............................................................................................................................................
............................................................................................................................................
............................................................................................................................................
............................................................................................................................................
............................................................................................................................................
............................................................................................................................................
............................................................................................................................................
............................................................................................................................................
............................................................................................................................................
............................................................................................................................................
............................................................................................................................................
............................................................................................................................................
............................................................................................................................................
............................................................................................................................................
............................................................................................................................................
............................................................................................................................................
............................................................................................................................................
............................................................................................................................................
............................................................................................................................................
............................................................................................................................................
............................................................................................................................................
............................................................................................................................................
...........................................................................................................................................D
ONE
Verifying https://github.com/kiwionly/elasticsearch-image/archive/master.zip checksums if available ...
NOTE: Unable to verify checksum for downloaded plugin (unable to find .sha1 or .md5 file to verify)
ERROR: Could not find plugin descriptor 'plugin-descriptor.properties' in plugin zip
```

What am I doing wrong ?

**Comment by Artgit** [comment]
Also, I have built plugin from source(Git master branch) by Gradle and unzipped following files :

```
elasticsearch-image-2.3.3.jar 
lire.jar 
metadata-extractor-2.8.1.jar 
plugin-descriptor.properties 
```

into 

`elasticsearch-2.3.3\plugins` folder

Right now during startup ES fails with a following error:

```
D:\Tools\elasticsearch-2.3.3\bin>elasticsearch.bat
[2016-07-02 14:54:54,248][WARN ][bootstrap                ] jvm uses the client vm, make sure to run `java` with the server vm for best perf
ormance by adding `-server` to the command line
[2016-07-02 14:54:54,389][INFO ][node                     ] [Sputnik] version[2.3.3], pid[15640], build[218bdf1/2016-05-17T15:40:04Z]
[2016-07-02 14:54:54,390][INFO ][node                     ] [Sputnik] initializing ...
Exception in thread "main" java.lang.IllegalStateException: Could not load plugin descriptor for existing plugin [elasticsearch-image-2.3.3.
jar]. Was the plugin built before 2.0?
Likely root cause: java.nio.file.NoSuchFileException: D:\Tools\elasticsearch-2.3.3\plugins\elasticsearch-image-2.3.3.jar\plugin-descriptor.p
roperties
        at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:79)
        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
        at sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:230)
        at java.nio.file.Files.newByteChannel(Files.java:361)
        at java.nio.file.Files.newByteChannel(Files.java:407)
        at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384)
        at java.nio.file.Files.newInputStream(Files.java:152)
        at org.elasticsearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:87)
        at org.elasticsearch.plugins.PluginsService.getPluginBundles(PluginsService.java:378)
        at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:128)
        at org.elasticsearch.node.Node.<init>(Node.java:158)
        at org.elasticsearch.node.Node.<init>(Node.java:140)
        at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:143)
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:178)
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:270)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)
Refer to the log for complete error details.

```

**Comment by kiwionly** [comment]
please build it manually, plugin command seem like not working.

I had update the readme.
